# Generated by Django 3.1.2 on 2021-12-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'gentleman'), ('F', 'kindgirl')], max_length=10)),
                ('username', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('introduction', models.CharField(max_length=100)),
                ('job', models.CharField(choices=[('ENGINEERING', 'ENGINEERING'), ('SALES', 'SALES'), ('HR', 'HR'), ('MARKETING', 'MARKETING')], max_length=20)),
            ],
        ),
    ]
