# Generated by Django 3.1.2 on 2021-12-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='gender',
            field=models.CharField(choices=[('M', 'man'), ('F', 'woman')], max_length=10),
        ),
        migrations.AlterField(
            model_name='members',
            name='job',
            field=models.CharField(choices=[('engineering', 'engineering'), ('sales', 'sales'), ('HR', 'HR'), ('marketing', 'marketing')], max_length=20),
        ),
    ]
