# Generated by Django 3.1.2 on 2021-12-23 01:38

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0002_auto_20211219_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='登録日時'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='members',
            name='age',
            field=models.IntegerField(verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='members',
            name='gender',
            field=models.CharField(choices=[('M', 'man'), ('F', 'woman')], max_length=10, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='members',
            name='introduction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='自己紹介文'),
        ),
        migrations.AlterField(
            model_name='members',
            name='job',
            field=models.CharField(choices=[('engineering', 'engineering'), ('sales', 'sales'), ('HR', 'HR'), ('marketing', 'marketing')], max_length=20, verbose_name='職業'),
        ),
        migrations.AlterField(
            model_name='members',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='名前'),
        ),
    ]
